name: qwen3
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.7.1
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - ld_impl_linux-aarch64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - openssl=3.0.16
  - parso=0.8.4
  - pexpect=4.8.0
  - pip=25.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.19.1
  - python=3.12.9
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - traitlets=5.14.3
  - tzdata=2025b
  - wcwidth=0.2.5
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.6.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - filelock==3.18.0
      - fsspec==2025.3.2
      - huggingface-hub==0.30.2
      - idna==3.10
      - jinja2==3.1.6
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.5
      - packaging==25.0
      - psutil==7.0.0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - safetensors==0.5.3
      - sympy==1.14.0
      - tokenizers==0.21.1
      - torch==2.7.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - typing-extensions==4.13.2
      - urllib3==2.4.0
